[platformio]
default_envs = rx1

[env:rx1]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_type = release

build_flags =
    -D TERRALINK_RX1
    -Wall
    -Wextra

lib_deps =
    plerup/EspSoftwareSerial@^8.0.1
