; ============================================================
; TERRALINK RECEIVER NODE
; ESP8266 RX1 + RX2
; ============================================================

[platformio]

; ============================================================
; RX1 - LoRa Gateway
; ESP8266 NodeMCU
; ============================================================

[env:rx1]

platform = espressif8266
board = nodemcuv2
framework = arduino

build_src_filter =
    +<ESP8266_Rx1.cpp>
    -<ESP8266_Rx2.cpp>

monitor_speed = 115200

lib_deps =
    sandeepmistry/LoRa@^0.8.0
    marcoschwartz/LiquidCrystal_I2C


; ============================================================
; RX2 - Command Console + Web Dashboard
; ESP8266 NodeMCU
; ============================================================

[env:rx2]

platform = espressif8266
board = nodemcuv2
framework = arduino

build_src_filter =
    +<ESP8266_Rx2.cpp>
    -<ESP8266_Rx1.cpp>

monitor_speed = 115200
