; ============================================================
; TERRALINK ROUTED RELAY NODE
; Arduino UNO + AI-Thinker RA-02 / SX1278
; ============================================================

[env:relay_uno]

platform = atmelavr
board = uno
framework = arduino

monitor_speed = 9600

lib_deps =
    sandeepmistry/LoRa@^0.8.0