#pragma once
typedef enum SystemState { STATE_AWAKENING, STATE_WAIT_RELEASE, STATE_READY, STATE_HOLDING_SOS, STATE_SOS_ACTIVATED, STATE_SENDING, STATE_WAITING_ACK, STATE_SOS_SUCCESS, STATE_SOS_FAILURE, STATE_POST_SOS, STATE_HOLDING_RESEND, STATE_RESCUE_MESSAGE } SystemState;
