#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "tl_packet.h"
static bool field(const char*raw,const char*name,char*out,uint16_t size){const char*p=raw;size_t n=strlen(name);if(size==0)return false;while(*p){if(strncmp(p,name,n)==0&&p[n]==':'){p+=n+1U;uint16_t i=0;while(*p&&*p!=','&&i+1U<size)out[i++]=*p++;out[i]='\0';return true;}while(*p&&*p!=',')p++;if(*p==',')p++;}return false;}
uint32_t tl_packet_field_u32(const char*r,const char*n,uint32_t f){char v[16];if(!field(r,n,v,sizeof(v)))return f;return strtoul(v,0,10);}
uint16_t tl_packet_field_u16(const char*r,const char*n,uint16_t f){return(uint16_t)tl_packet_field_u32(r,n,f);}
uint8_t tl_packet_field_u8(const char*r,const char*n,uint8_t f){return(uint8_t)tl_packet_field_u32(r,n,f);}
uint8_t tl_packet_get_from(const char*r){return tl_packet_field_u8(r,"FROM",0);}
uint8_t tl_packet_get_next(const char*r){return tl_packet_field_u8(r,"NEXT",TL_BROADCAST_ID);}
static TLPacketType type_of(const char*r){char v[12];if(!field(r,"TYPE",v,sizeof(v)))return TL_TYPE_UNKNOWN;if(!strcmp(v,"SOS"))return TL_TYPE_SOS;if(!strcmp(v,"ACK"))return TL_TYPE_ACK;if(!strcmp(v,"MSG"))return TL_TYPE_MSG;if(!strcmp(v,"MSGACK"))return TL_TYPE_MSGACK;if(!strcmp(v,"LOCREQ"))return TL_TYPE_LOCREQ;if(!strcmp(v,"LOC"))return TL_TYPE_LOC;if(!strcmp(v,"HELLO"))return TL_TYPE_HELLO;return TL_TYPE_UNKNOWN;}
const char*tl_packet_type_name(TLPacketType t){switch(t){case TL_TYPE_SOS:return"SOS";case TL_TYPE_ACK:return"ACK";case TL_TYPE_MSG:return"MSG";case TL_TYPE_MSGACK:return"MSGACK";case TL_TYPE_LOCREQ:return"LOCREQ";case TL_TYPE_LOC:return"LOC";case TL_TYPE_HELLO:return"HELLO";default:return"UNKNOWN";}}
bool tl_packet_parse(const char*r,TLPacket*p){memset(p,0,sizeof(*p));p->src=tl_packet_field_u8(r,"SRC",0);p->dst=tl_packet_field_u8(r,"DST",0);p->seq=tl_packet_field_u32(r,"SEQ",0);p->ttl=tl_packet_field_u8(r,"TTL",0);p->hop=tl_packet_field_u8(r,"HOP",255);p->from=tl_packet_get_from(r);p->next=tl_packet_get_next(r);p->msg_id=tl_packet_field_u16(r,"MSGID",0);char tmp[12];p->has_msg_id=field(r,"MSGID",tmp,sizeof(tmp));field(r,"LAT",p->lat,sizeof(p->lat));field(r,"LON",p->lon,sizeof(p->lon));field(r,"MSG",p->msg,sizeof(p->msg));p->type=type_of(r);p->valid=(p->src&&p->dst&&p->ttl&&p->hop<=TL_MAX_TTL&&p->type!=TL_TYPE_UNKNOWN);return p->valid;}
bool tl_packet_build_forward(const char*o,char*out,uint16_t size,uint8_t ttl,uint8_t hop,uint8_t next){char src[8],dst[8],seq[16],type[12];if(!field(o,"SRC",src,sizeof(src))||!field(o,"DST",dst,sizeof(dst))||!field(o,"SEQ",seq,sizeof(seq))||!field(o,"TYPE",type,sizeof(type)))return false;int n=snprintf(out,size,"SRC:%s,DST:%s,SEQ:%s,TTL:%u,HOP:%u,NEXT:%u,FROM:%u,TYPE:%s",src,dst,seq,ttl,hop,next,TL_RELAY_NODE_ID,type);if(n<0||(uint16_t)n>=size)return false;size_t used=strlen(out),rem=size-used;if(!strcmp(type,"SOS")||!strcmp(type,"LOC")){char lat[20],lon[20];if(!field(o,"LAT",lat,sizeof(lat))||!field(o,"LON",lon,sizeof(lon)))return false;n=snprintf(out+used,rem,",LAT:%s,LON:%s",lat,lon);}else if(!strcmp(type,"MSG")){char id[10],msg[81];if(!field(o,"MSGID",id,sizeof(id)))return false;if(!field(o,"MSG",msg,sizeof(msg)))msg[0]=0;n=snprintf(out+used,rem,",MSGID:%s,MSG:%s",id,msg);}else if(!strcmp(type,"MSGACK")||!strcmp(type,"LOCREQ")){char id[10];if(field(o,"MSGID",id,sizeof(id)))n=snprintf(out+used,rem,",MSGID:%s",id);else n=0;}else n=0;return n>=0&&(size_t)n<rem;}
